platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
}

def flutter_install_all_ios_pods(flutter_application_path)
  use_frameworks!
  pod 'Flutter', :path => File.join(flutter_application_path, '.ios', 'Flutter')
end

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
